# Generated by Django 4.2.1 on 2023-05-25 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('nombre', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('idReparacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(default='foto/default.avif', null=True, upload_to='foto')),
                ('publicar', models.BooleanField(default=False)),
                ('comentario', models.TextField(default='S/C')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webTaller.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
