# Generated by Django 4.1.5 on 2023-05-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webTaller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='usuario',
        ),
    ]
